# This is refering to the base image and providing the files at the runtime
# Whenever this image is being built the built triggers will executed and install the npm and bower packages.
FROM upuldi/onbuilt_demo
