#When you are using CMD you can overrider the default command in runtime 
FROM ubuntu
MAINTAINER upuldi@gmail.com
RUN apt-get update && apt-get install iputils-ping  --assume-yes 
CMD ["ping","www.google.com"]
