#When you are using CMD you can overrider the default command in runtime 
FROM buildpack
MAINTAINER upuldi@gmail.com
RUN culr -SL http://mirror.intergrid.com.au/apache/tomcat/tomcat-7/v7.0.85/bin/apache-tomcat-7.0.85.tar.gz \ 
| tar -zxC /opt
